# Generated by Django 4.2.4 on 2023-10-17 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('author_affiliations', models.TextField(blank=True, null=True)),
                ('publication_title', models.TextField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('ai_abstract_summary', models.TextField(blank=True, null=True)),
                ('author_keywords', models.TextField(blank=True, null=True)),
                ('ai_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('topic_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'research_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicToKeywords',
            fields=[
                ('topic_number', models.IntegerField(primary_key=True, serialize=False)),
                ('ai_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
            ],
            options={
                'db_table': 'topic_to_keywords',
                'managed': False,
            },
        ),
    ]
